package edu.sjsu.cmpe275.entities;

// Generated Nov 22, 2015 8:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import edu.sjsu.cmpe275.entities.Person;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON", catalog = "CMPE275_PROJECT_MGMT_DB", uniqueConstraints = @UniqueConstraint(columnNames = "EMAILID"))
public class Person implements java.io.Serializable {

	private int personId;
	private String name;
	private String password;
	private String emailid;
	private String description;
	
	//Person can own multiple projects
	@OneToMany(fetch = FetchType.LAZY, mappedBy="PERSON_ID", cascade=CascadeType.ALL)  
	private List<Project> ownedProjects=new ArrayList<Project>();
	
	
	//Many projects are shared with many users
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "SharedProjects", joinColumns = @JoinColumn(name ="PERSON_ID"), 
	inverseJoinColumns = @JoinColumn(name = "SHARED_PRSN_ID"))
	private List<Project> sharedProjects=new ArrayList<Project>();
	
	

	//Constructors
	public Person() {
	}

	public Person(String name, String password, String emailid) {
		this.name = name;
		this.password = password;
		this.emailid = emailid;
	}

	public Person(String name, String password, String emailid,
			String description) {
		this.name = name;
		this.password = password;
		this.emailid = emailid;
		this.description = description;
	}

	
	//Getter-Setter methods
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PERSON_ID", unique = true, nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAILID", unique = true, nullable = false, length = 45)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Transient
	public List<Project> getOwnedProjects() {
		return ownedProjects;
	}

	public void setOwnedProjects(List<Project> ownedProjects) {
		this.ownedProjects = ownedProjects;
	}

	@Transient
	public List<Project> getSharedProjects() {
		return sharedProjects;
	}

	public void setSharedProjects(List<Project> sharedProjects) {
		this.sharedProjects = sharedProjects;
	}


}
