package edu.sjsu.cmpe275.entities;

// Generated Nov 22, 2015 8:22:29 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SharedProjects generated by hbm2java
 */
@Entity
@Table(name = "SHARED_PROJECTS", catalog = "CMPE275_PROJECT_MGMT_DB")
public class SharedProjects implements java.io.Serializable {

	private int sharedPrjctId;
	private int sharedPrsnId;
	private char acceptedFlag;
	private Project project;
	
	
	

	@ManyToOne(cascade = CascadeType.PERSIST)
	@JoinColumn(name ="SHARED_PRJCT_ID")
	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	
	
	public SharedProjects() {
	}

	public SharedProjects(int sharedPrjctId, int sharedPrsnId) {
		this.sharedPrjctId = sharedPrjctId;
		this.sharedPrsnId = sharedPrsnId;
		this.acceptedFlag = 'N';
	}

	public SharedProjects(int sharedPrjctId, int sharedPrsnId,char acceptedFlag) {
		this.sharedPrjctId = sharedPrjctId;
		this.sharedPrsnId = sharedPrsnId;
		this.acceptedFlag = acceptedFlag;
	}
	
	
	//Fields
	@Id
	@Column(name = "SHARED_PRJCT_ID", nullable = false)
	public int getSharedPrjctId() {
		return this.sharedPrjctId;
	}

	public void setSharedPrjctId(int sharedPrjctId) {
		this.sharedPrjctId = sharedPrjctId;
	}

	@Id
	@Column(name = "SHARED_PRSN_ID", nullable = false)
	public int getSharedPrsnId() {
		return this.sharedPrsnId;
	}

	public void setSharedPrsnId(int sharedPrsnId) {
		this.sharedPrsnId = sharedPrsnId;
	}

	@Column(name = "ACCEPTED_FLAG", nullable = false, length = 1)
	public char getAcceptedFlag() {
		return this.acceptedFlag;
	}

	public void setAcceptedFlag(char acceptedFlag) {
		this.acceptedFlag = acceptedFlag;
	}

}
